name: Katalon Test Execution

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Katalon Studio
        uses: katalon-studio/setup-katalon-studio@v1
        with:
          version: "9.0.0"  # Change to the latest version

      - name: Run Katalon Tests
        run: |
          katalonc -noSplash -runMode=console \
          -projectPath="$(pwd)/CrediteVile Assesment/CrediteVile Assesment.prj" \
          -testSuitePath="Test Suites/Assessment" \
          -browserType="Chrome"
