name: Katalon Studio Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install Java and Katalon Studio dependencies
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://download.katalon.com/9.0.0/Katalon_Studio_Linux_64-9.0.0.tar.gz
          tar -xzf Katalon_Studio_Linux_64-9.0.0.tar.gz -C /home/runner/work/katalonStudio-Project/katalonStudio-Project/ --strip-components=1
      

      - name: Debug environment variables
        run: |
          echo "PATH: $PATH"
          echo "JAVA_HOME: $JAVA_HOME"
          ls -l /home/runner/work/katalonStudio-Project/katalonStudio-Project/


      - name: Verify Katalon Studio installation
        run: |
          /home/runner/work/katalonStudio-Project/katalonStudio-Project/katalon -version


      - name: Run Katalon Studio test
        run: |
          /home/runner/work/katalonStudio-Project/katalonStudio-Project/katalon \
            -noSplash \
            -runMode=console \
            -projectPath="/home/runner/work/katalonStudio-Project/katalonStudio-Project/CrediteVile Assesment/CrediteVile Assesment.prj" \
            -testSuitePath="Test Suites/Assessment" \
            -browserType="Chrome"
      


