name: Run Katalon Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  katalon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Katalon
        run: |
          mkdir -p katalon
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.2.5/katalon-studio-linux-64.zip -O katalon-studio-linux-64.zip
          unzip katalon-studio-linux-64.zip -d katalon

      - name: Verify download
        run: |
          file katalon-studio-linux-64.zip

      - name: Run Katalon Studio
        run: |
          $HOME/katalon/katalonc -noSplash -runMode=console -projectPath="C:/Users/mdpas/Katalon Studio/CrediteVile Assesment" -retry=0 -testSuitePath="Test Suites/Assessment" -executionProfile="default" -browserType="Chrome"
