name: Katalon Automation

on:
  push:  # This runs the workflow when you push changes
    branches:
      - main
  workflow_dispatch:  # ✅ This allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Katalon
        run: |
          wget -q https://download.katalon.com/9.0.0/Katalon_Studio_Linux_64-9.0.0.tar.gz
          tar -xzf Katalon_Studio_Linux_64-9.0.0.tar.gz
          mv Katalon_Studio_Linux_64-9.0.0 Katalon_Studio_Linux_64
          chmod +x Katalon_Studio_Linux_64/katalonc

      - name: Run Katalon Test
        run: |
          xvfb-run --auto-servernum Katalon_Studio_Linux_64/katalonc \
          -noSplash -runMode=console \
          -projectPath="$(pwd)/CrediteVile Assesment/CrediteVile Assesment.prj" \
          -testSuitePath="Test Suites/Assessment" \
          -browserType="Chrome"
