name: Katalon Studio Test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  katalon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Download Katalon
      run: |
        mkdir -p katalon
        curl -L https://github.com/katalon-studio/katalon-studio/releases/download/v8.2.5/katalon-studio-linux-64.zip -o katalon-studio-linux-64.zip
        unzip katalon-studio-linux-64.zip -d katalon

    - name: Run Katalon Studio Tests
      run: |
        katalon/katalonc -noSplash -runMode=console |
          $HOME/Katalon_Studio_Linux_64-8.2.5/katalonc -noSplash -runMode=console -projectPath="C:/Users/mdpas/Katalon Studio/CrediteVile Assesment" -retry=0 -testSuitePath=Test Suites/Assessment -executionProfile=default -browserType=Chrome

